# Form implementation generated from reading ui file 'ana.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(972, 583)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/nglogo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-image: url(res/gradient.png);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(280, 20, 671, 71))
        self.widget.setStyleSheet("\n"
" background: transparent !important;")
        self.widget.setObjectName("widget")
        self.layoutWidget = QtWidgets.QWidget(parent=self.widget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 646, 57))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.home = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.home.setMinimumSize(QtCore.QSize(51, 51))
        self.home.setStyleSheet("\n"
" background: transparent !important;")
        self.home.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("res/house.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.home.setIcon(icon1)
        self.home.setIconSize(QtCore.QSize(51, 51))
        self.home.setObjectName("home")
        self.horizontalLayout_2.addWidget(self.home)
        self.deal = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.deal.setMinimumSize(QtCore.QSize(51, 51))
        self.deal.setStyleSheet("\n"
" background: transparent !important;")
        self.deal.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("res/deal.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.deal.setIcon(icon2)
        self.deal.setIconSize(QtCore.QSize(51, 51))
        self.deal.setObjectName("deal")
        self.horizontalLayout_2.addWidget(self.deal)
        self.date = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.date.setMinimumSize(QtCore.QSize(51, 51))
        self.date.setStyleSheet("\n"
" background: transparent !important;")
        self.date.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("res/calendar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.date.setIcon(icon3)
        self.date.setIconSize(QtCore.QSize(51, 51))
        self.date.setObjectName("date")
        self.horizontalLayout_2.addWidget(self.date)
        self.task = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.task.setMinimumSize(QtCore.QSize(51, 51))
        self.task.setStyleSheet("\n"
" background: transparent !important;")
        self.task.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("res/task.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.task.setIcon(icon4)
        self.task.setIconSize(QtCore.QSize(51, 51))
        self.task.setObjectName("task")
        self.horizontalLayout_2.addWidget(self.task)
        self.client = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.client.setMinimumSize(QtCore.QSize(51, 51))
        self.client.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.client.setStyleSheet("\n"
" background: transparent !important;")
        self.client.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("res/client.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.client.setIcon(icon5)
        self.client.setIconSize(QtCore.QSize(51, 51))
        self.client.setObjectName("client")
        self.horizontalLayout_2.addWidget(self.client)
        self.empl = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.empl.setMinimumSize(QtCore.QSize(51, 51))
        self.empl.setStyleSheet("\n"
" background: transparent !important;")
        self.empl.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("res/emp.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.empl.setIcon(icon6)
        self.empl.setIconSize(QtCore.QSize(51, 51))
        self.empl.setObjectName("empl")
        self.horizontalLayout_2.addWidget(self.empl)
        self.chat = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.chat.setMinimumSize(QtCore.QSize(51, 51))
        self.chat.setStyleSheet("\n"
" background: transparent !important;")
        self.chat.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("res/chat.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.chat.setIcon(icon7)
        self.chat.setIconSize(QtCore.QSize(51, 51))
        self.chat.setObjectName("chat")
        self.horizontalLayout_2.addWidget(self.chat)
        self.ana = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.ana.setMinimumSize(QtCore.QSize(51, 51))
        self.ana.setStyleSheet("\n"
" background: transparent !important;")
        self.ana.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("res/an.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.ana.setIcon(icon8)
        self.ana.setIconSize(QtCore.QSize(51, 51))
        self.ana.setObjectName("ana")
        self.horizontalLayout_2.addWidget(self.ana)
        self.sett = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.sett.setMinimumSize(QtCore.QSize(51, 51))
        self.sett.setStyleSheet("\n"
" background: transparent !important;")
        self.sett.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("res/set.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.sett.setIcon(icon9)
        self.sett.setIconSize(QtCore.QSize(51, 51))
        self.sett.setObjectName("sett")
        self.horizontalLayout_2.addWidget(self.sett)
        self.notification = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.notification.setMinimumSize(QtCore.QSize(51, 51))
        self.notification.setStyleSheet("\n"
" background: transparent !important;")
        self.notification.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("res/uved.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.notification.setIcon(icon10)
        self.notification.setIconSize(QtCore.QSize(51, 51))
        self.notification.setObjectName("notification")
        self.horizontalLayout_2.addWidget(self.notification)
        self.help = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.help.setMinimumSize(QtCore.QSize(51, 51))
        self.help.setStyleSheet("\n"
" background: transparent !important;")
        self.help.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("res/que.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.help.setIcon(icon11)
        self.help.setIconSize(QtCore.QSize(51, 51))
        self.help.setObjectName("help")
        self.horizontalLayout_2.addWidget(self.help)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 261, 81))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("res/ngname.png"))
        self.label.setObjectName("label")
        self.widget_5 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_5.setGeometry(QtCore.QRect(700, 440, 241, 131))
        self.widget_5.setStyleSheet("    background: transparent !important;")
        self.widget_5.setObjectName("widget_5")
        self.layoutWidget_2 = QtWidgets.QWidget(parent=self.widget_5)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 10, 231, 111))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.profil = QtWidgets.QLabel(parent=self.layoutWidget_2)
        self.profil.setStyleSheet("background: transparent !important;\n"
"font: 500 12pt \"Segoe UI\";\n"
"")
        self.profil.setObjectName("profil")
        self.verticalLayout_2.addWidget(self.profil)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.layoutWidget_2)
        self.pushButton_2.setMinimumSize(QtCore.QSize(181, 51))
        self.pushButton_2.setMaximumSize(QtCore.QSize(181, 51))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"font: 625 14pt \"Segoe UI\";\n"
"background: #94a5ff;\n"
"border-radius: 20px;   \n"
"                  /* <----  20px  */ \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background:#E1E5FF;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: #717ec3;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Аналитика"))
        self.profil.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "Выйти"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
