# Form implementation generated from reading ui file 'auth.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(972, 583)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/nglogo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background: url(res/gradient.png);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 261, 81))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("res/ngname.png"))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(360, 140, 241, 41))
        self.label_3.setMinimumSize(QtCore.QSize(241, 41))
        self.label_3.setMaximumSize(QtCore.QSize(241, 41))
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet("font: 700 18pt \"Segoe UI\";\n"
"    background: transparent !important;\n"
"\n"
"")
        self.label_3.setObjectName("label_3")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(390, 370, 181, 51))
        self.pushButton_3.setMinimumSize(QtCore.QSize(181, 51))
        self.pushButton_3.setMaximumSize(QtCore.QSize(181, 51))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"font: 625 14pt \"Segoe UI\";\n"
"background: #94a5ff;\n"
"border-radius: 20px;   \n"
"                  /* <----  20px  */ \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background:#E1E5FF;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: #717ec3;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(295, 186, 381, 211))
        self.widget.setMinimumSize(QtCore.QSize(381, 211))
        self.widget.setMaximumSize(QtCore.QSize(381, 211))
        self.widget.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.widget.setAutoFillBackground(False)
        self.widget.setStyleSheet("\n"
"background: rgb(255, 255, 255);\n"
"\n"
"border-radius: 20px;                     /* <----  20px  */ ")
        self.widget.setObjectName("widget")
        self.layoutWidget = QtWidgets.QWidget(parent=self.widget)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 30, 271, 143))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ngname_2 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.ngname_2.setMinimumSize(QtCore.QSize(31, 31))
        self.ngname_2.setMaximumSize(QtCore.QSize(31, 31))
        self.ngname_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ngname_2.setText("")
        self.ngname_2.setPixmap(QtGui.QPixmap("res/human.png"))
        self.ngname_2.setScaledContents(True)
        self.ngname_2.setObjectName("ngname_2")
        self.horizontalLayout_2.addWidget(self.ngname_2)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit.setMinimumSize(QtCore.QSize(221, 51))
        self.lineEdit.setMaximumSize(QtCore.QSize(221, 51))
        self.lineEdit.setStyleSheet("font: 12pt \"Nirmala UI\";\n"
"border-radius: 15px;                     /* <----  20px  */ \n"
"border: 2px solid #94a5ff;\n"
"    background: transparent !important;\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ngname_3 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.ngname_3.setMinimumSize(QtCore.QSize(31, 31))
        self.ngname_3.setMaximumSize(QtCore.QSize(31, 31))
        self.ngname_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ngname_3.setText("")
        self.ngname_3.setPixmap(QtGui.QPixmap("res/lock.png"))
        self.ngname_3.setScaledContents(True)
        self.ngname_3.setObjectName("ngname_3")
        self.horizontalLayout_3.addWidget(self.ngname_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(221, 51))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(221, 51))
        self.lineEdit_2.setStyleSheet("font: 12pt \"Nirmala UI\";\n"
"border-radius: 15px;                     /* <----  20px  */ \n"
"border: 2px solid #94a5ff;\n"
"    background: transparent !important;")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(121, 21))
        self.pushButton_2.setMaximumSize(QtCore.QSize(121, 21))
        self.pushButton_2.setStyleSheet("\n"
"QPushButton{\n"
"font: 10pt \"Segoe UI\";\n"
"background: transparent !important;\n"
"border: 2px solid rgb(255, 255, 255);\n"
"color:rgb(107, 107, 107)\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color:rgb(84, 84, 84);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.label.raise_()
        self.label_3.raise_()
        self.widget.raise_()
        self.pushButton_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Вход"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Вход в систему</p><p align=\"center\"><br/></p></body></html>"))
        self.pushButton_3.setText(_translate("MainWindow", "Войти"))
        self.lineEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Электронная почта"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Пароль"))
        self.pushButton_2.setText(_translate("MainWindow", "Забыли пароль?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
