# Form implementation generated from reading ui file 'recovery.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(972, 583)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/nglogo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background: url(res/gradient.png);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 261, 81))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("res/ngname.png"))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(360, 140, 241, 41))
        self.label_3.setMinimumSize(QtCore.QSize(241, 41))
        self.label_3.setMaximumSize(QtCore.QSize(241, 41))
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet("font: 700 18pt \"Segoe UI\";\n"
"    background: transparent !important;\n"
"\n"
"")
        self.label_3.setObjectName("label_3")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(295, 186, 381, 211))
        self.widget.setMinimumSize(QtCore.QSize(381, 211))
        self.widget.setMaximumSize(QtCore.QSize(381, 211))
        self.widget.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.widget.setAutoFillBackground(False)
        self.widget.setStyleSheet("\n"
"background: rgb(255, 255, 255);\n"
"\n"
"border-radius: 20px;                     /* <----  20px  */ ")
        self.widget.setObjectName("widget")
        self.widget1 = QtWidgets.QWidget(parent=self.widget)
        self.widget1.setGeometry(QtCore.QRect(50, 80, 271, 81))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ngname_2 = QtWidgets.QLabel(parent=self.widget1)
        self.ngname_2.setMinimumSize(QtCore.QSize(31, 31))
        self.ngname_2.setMaximumSize(QtCore.QSize(31, 31))
        self.ngname_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ngname_2.setText("")
        self.ngname_2.setPixmap(QtGui.QPixmap("res/human.png"))
        self.ngname_2.setScaledContents(True)
        self.ngname_2.setObjectName("ngname_2")
        self.horizontalLayout_2.addWidget(self.ngname_2)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.widget1)
        self.lineEdit.setMinimumSize(QtCore.QSize(221, 51))
        self.lineEdit.setMaximumSize(QtCore.QSize(221, 51))
        self.lineEdit.setStyleSheet("font: 12pt \"Nirmala UI\";\n"
"border-radius: 15px;                     /* <----  20px  */ \n"
"border: 2px solid #94a5ff;\n"
"    background: transparent !important;\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setGeometry(QtCore.QRect(60, 10, 261, 31))
        self.label_2.setStyleSheet("font: 500 10pt \"Segoe UI\";\n"
"    background: transparent !important;")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(parent=self.widget)
        self.label_4.setGeometry(QtCore.QRect(80, 30, 261, 31))
        self.label_4.setStyleSheet("font: 500 10pt \"Segoe UI\";\n"
"    background: transparent !important;")
        self.label_4.setObjectName("label_4")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(490, 380, 181, 51))
        self.pushButton_4.setMinimumSize(QtCore.QSize(181, 51))
        self.pushButton_4.setMaximumSize(QtCore.QSize(181, 51))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"font: 625 14pt \"Segoe UI\";\n"
"background: #94a5ff;\n"
"border-radius: 20px;   \n"
"                  /* <----  20px  */ \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background:#E1E5FF;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: #717ec3;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(300, 380, 181, 51))
        self.pushButton_3.setMinimumSize(QtCore.QSize(181, 51))
        self.pushButton_3.setMaximumSize(QtCore.QSize(181, 51))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"font: 625 14pt \"Segoe UI\";\n"
"background: #94a5ff;\n"
"border-radius: 20px;   \n"
"                  /* <----  20px  */ \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background:#E1E5FF;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: #717ec3;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Восстановление"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Восстановление</p><p align=\"center\"><br/></p></body></html>"))
        self.lineEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Электронная почта"))
        self.label_2.setText(_translate("MainWindow", "Введите почту к которой привязан аккаунт"))
        self.label_4.setText(_translate("MainWindow", "На неё вам придет новый пароль"))
        self.pushButton_4.setText(_translate("MainWindow", "Отмена"))
        self.pushButton_3.setText(_translate("MainWindow", "Восстановить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
