# Form implementation generated from reading ui file 'tasks.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(992, 673)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../crm/res/nglogo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-image: url(res/gradient.png);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(510, 580, 171, 51))
        self.pushButton.setStyleSheet("QPushButton{\n"
"font: 625 10pt \"Segoe UI\";\n"
"background: #94a5ff;\n"
"border-radius: 20px;   \n"
"                  /* <----  20px  */ \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background:#E1E5FF;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: #717ec3;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layoutWidget1 = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(290, 10, 671, 71))
        self.widget.setStyleSheet("\n"
" background: transparent !important;")
        self.widget.setObjectName("widget")
        self.layoutWidget_2 = QtWidgets.QWidget(parent=self.widget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 10, 646, 57))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.home_2 = QtWidgets.QPushButton(parent=self.layoutWidget_2)
        self.home_2.setMinimumSize(QtCore.QSize(51, 51))
        self.home_2.setStyleSheet("\n"
" background: transparent !important;")
        self.home_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("res/house.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.home_2.setIcon(icon1)
        self.home_2.setIconSize(QtCore.QSize(51, 51))
        self.home_2.setObjectName("home_2")
        self.horizontalLayout_3.addWidget(self.home_2)
        self.deal_2 = QtWidgets.QPushButton(parent=self.layoutWidget_2)
        self.deal_2.setMinimumSize(QtCore.QSize(51, 51))
        self.deal_2.setStyleSheet("\n"
" background: transparent !important;")
        self.deal_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("res/deal.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.deal_2.setIcon(icon2)
        self.deal_2.setIconSize(QtCore.QSize(51, 51))
        self.deal_2.setObjectName("deal_2")
        self.horizontalLayout_3.addWidget(self.deal_2)
        self.date_2 = QtWidgets.QPushButton(parent=self.layoutWidget_2)
        self.date_2.setMinimumSize(QtCore.QSize(51, 51))
        self.date_2.setStyleSheet("\n"
" background: transparent !important;")
        self.date_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("res/calendar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.date_2.setIcon(icon3)
        self.date_2.setIconSize(QtCore.QSize(51, 51))
        self.date_2.setObjectName("date_2")
        self.horizontalLayout_3.addWidget(self.date_2)
        self.task_2 = QtWidgets.QPushButton(parent=self.layoutWidget_2)
        self.task_2.setMinimumSize(QtCore.QSize(51, 51))
        self.task_2.setStyleSheet("\n"
" background: transparent !important;")
        self.task_2.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("res/task.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.task_2.setIcon(icon4)
        self.task_2.setIconSize(QtCore.QSize(51, 51))
        self.task_2.setObjectName("task_2")
        self.horizontalLayout_3.addWidget(self.task_2)
        self.client_2 = QtWidgets.QPushButton(parent=self.layoutWidget_2)
        self.client_2.setMinimumSize(QtCore.QSize(51, 51))
        self.client_2.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.client_2.setStyleSheet("\n"
" background: transparent !important;")
        self.client_2.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("res/client.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.client_2.setIcon(icon5)
        self.client_2.setIconSize(QtCore.QSize(51, 51))
        self.client_2.setObjectName("client_2")
        self.horizontalLayout_3.addWidget(self.client_2)
        self.empl_2 = QtWidgets.QPushButton(parent=self.layoutWidget_2)
        self.empl_2.setMinimumSize(QtCore.QSize(51, 51))
        self.empl_2.setStyleSheet("\n"
" background: transparent !important;")
        self.empl_2.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("res/emp.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.empl_2.setIcon(icon6)
        self.empl_2.setIconSize(QtCore.QSize(51, 51))
        self.empl_2.setObjectName("empl_2")
        self.horizontalLayout_3.addWidget(self.empl_2)
        self.chat_2 = QtWidgets.QPushButton(parent=self.layoutWidget_2)
        self.chat_2.setMinimumSize(QtCore.QSize(51, 51))
        self.chat_2.setStyleSheet("\n"
" background: transparent !important;")
        self.chat_2.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("res/chat.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.chat_2.setIcon(icon7)
        self.chat_2.setIconSize(QtCore.QSize(51, 51))
        self.chat_2.setObjectName("chat_2")
        self.horizontalLayout_3.addWidget(self.chat_2)
        self.ana_2 = QtWidgets.QPushButton(parent=self.layoutWidget_2)
        self.ana_2.setMinimumSize(QtCore.QSize(51, 51))
        self.ana_2.setStyleSheet("\n"
" background: transparent !important;")
        self.ana_2.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("res/an.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.ana_2.setIcon(icon8)
        self.ana_2.setIconSize(QtCore.QSize(51, 51))
        self.ana_2.setObjectName("ana_2")
        self.horizontalLayout_3.addWidget(self.ana_2)
        self.sett_2 = QtWidgets.QPushButton(parent=self.layoutWidget_2)
        self.sett_2.setMinimumSize(QtCore.QSize(51, 51))
        self.sett_2.setStyleSheet("\n"
" background: transparent !important;")
        self.sett_2.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("res/set.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.sett_2.setIcon(icon9)
        self.sett_2.setIconSize(QtCore.QSize(51, 51))
        self.sett_2.setObjectName("sett_2")
        self.horizontalLayout_3.addWidget(self.sett_2)
        self.notification_2 = QtWidgets.QPushButton(parent=self.layoutWidget_2)
        self.notification_2.setMinimumSize(QtCore.QSize(51, 51))
        self.notification_2.setStyleSheet("\n"
" background: transparent !important;")
        self.notification_2.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("res/uved.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.notification_2.setIcon(icon10)
        self.notification_2.setIconSize(QtCore.QSize(51, 51))
        self.notification_2.setObjectName("notification_2")
        self.horizontalLayout_3.addWidget(self.notification_2)
        self.help_2 = QtWidgets.QPushButton(parent=self.layoutWidget_2)
        self.help_2.setMinimumSize(QtCore.QSize(51, 51))
        self.help_2.setStyleSheet("\n"
" background: transparent !important;")
        self.help_2.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("res/que.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.help_2.setIcon(icon11)
        self.help_2.setIconSize(QtCore.QSize(51, 51))
        self.help_2.setObjectName("help_2")
        self.horizontalLayout_3.addWidget(self.help_2)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 261, 81))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("res/ngname.png"))
        self.label.setObjectName("label")
        self.profil = QtWidgets.QLabel(parent=self.centralwidget)
        self.profil.setGeometry(QtCore.QRect(770, 510, 229, 52))
        self.profil.setStyleSheet("background: transparent !important;\n"
"font: 500 12pt \"Segoe UI\";\n"
"")
        self.profil.setObjectName("profil")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(790, 580, 181, 51))
        self.pushButton_2.setMinimumSize(QtCore.QSize(181, 51))
        self.pushButton_2.setMaximumSize(QtCore.QSize(181, 51))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"font: 625 10pt \"Segoe UI\";\n"
"background: #94a5ff;\n"
"border-radius: 20px;   \n"
"                  /* <----  20px  */ \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background:#E1E5FF;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: #717ec3;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.widget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(21, 148, 459, 202))
        self.widget_2.setStyleSheet("padding: 2px;\n"
"    margin: 2px;\n"
" background: transparent !important;\n"
"    background: rgb(255, 255, 255);\n"
"    font: 500 14pt \"Segoe UI\";\n"
"    border-radius: 10px;\n"
"    box-shadow: 0px 10px 30px rgba(0, 0, 0, 0.3);\n"
"\n"
"\n"
"\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(21, 101, 251, 41))
        self.label_3.setMinimumSize(QtCore.QSize(251, 41))
        self.label_3.setMaximumSize(QtCore.QSize(251, 41))
        self.label_3.setStyleSheet("background: transparent !important;\n"
"font: 600 12pt \"Segoe UI\";")
        self.label_3.setObjectName("label_3")
        self.widget_6 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_6.setGeometry(QtCore.QRect(511, 148, 459, 202))
        self.widget_6.setStyleSheet("padding: 2px;\n"
"    margin: 2px;\n"
" background: transparent !important;\n"
"    background: rgb(255, 255, 255);\n"
"    font: 500 14pt \"Segoe UI\";\n"
"    border-radius: 10px;\n"
"    box-shadow: 0px 10px 30px rgba(0, 0, 0, 0.3);\n"
"\n"
"\n"
"\n"
"")
        self.widget_6.setObjectName("widget_6")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(511, 101, 251, 41))
        self.label_5.setMinimumSize(QtCore.QSize(251, 41))
        self.label_5.setMaximumSize(QtCore.QSize(251, 41))
        self.label_5.setStyleSheet("background: transparent !important;\n"
"font: 600 12pt \"Segoe UI\";")
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(21, 381, 251, 41))
        self.label_4.setMinimumSize(QtCore.QSize(251, 41))
        self.label_4.setMaximumSize(QtCore.QSize(251, 41))
        self.label_4.setStyleSheet("background: transparent !important;\n"
"font: 600 12pt \"Segoe UI\";\n"
"")
        self.label_4.setObjectName("label_4")
        self.widget_4 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_4.setGeometry(QtCore.QRect(21, 428, 459, 202))
        self.widget_4.setStyleSheet("padding: 2px;\n"
"    margin: 2px;\n"
" background: transparent !important;\n"
"    background: rgb(255, 255, 255);\n"
"    font: 500 14pt \"Segoe UI\";\n"
"    border-radius: 10px;\n"
"    box-shadow: 0px 10px 30px rgba(0, 0, 0, 0.3);\n"
"\n"
"\n"
"\n"
"")
        self.widget_4.setObjectName("widget_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Задачи"))
        self.pushButton.setText(_translate("MainWindow", "СОЗДАТЬ НОВУЮ"))
        self.profil.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "ВЫЙТИ"))
        self.label_3.setText(_translate("MainWindow", "ПРОСРОЧЕННЫЕ ЗАДАЧИ"))
        self.label_5.setText(_translate("MainWindow", "ЗАДАЧИ НА БУДУЩЕЕ"))
        self.label_4.setText(_translate("MainWindow", "ЗАДАЧИ НА СЕГОДНЯ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
